---
- name: Setup timezone
  community.general.timezone:
    name: America/Fortaleza
  notify: Restart cron

- name: Run notified handlers
  ansible.builtin.meta: flush_handlers

- name: Add /etc/hosts content
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ puppet_agent_ip }} {{ puppet_agent_fqdn }} {{ puppet_agent_hostname }}
      {{ puppet_server_ip }} {{ puppet_server_fqdn }} {{ puppet_server_hostname }}
    state: present

- name: Server setup
  ansible.builtin.include_tasks:
    file: setup_server.yml
  when: inventory_hostname == "server"

- name: Agent setup
  ansible.builtin.include_tasks:
    file: setup_agent.yml
  when: inventory_hostname == "agent-ubuntu"

- name: Ssl bootstrap
  ansible.builtin.include_tasks:
    file: ssl_bootstrap.yml

- name: Copy modules and manifests
  ansible.builtin.include_tasks:
    file: modules_manifests.yml
  when: inventory_hostname == "server"

# There are errors, but it runs
- name: Run Puppet
  # trunk-ignore(yamllint/empty-values)
  community.general.puppet:
  when: inventory_hostname == "agent-ubuntu"
