---
- name: Create LAMP module dir
  ansible.builtin.file:
    path: "{{ puppet_modules_dir }}/lamp/manifests"
    mode: "0755"
    state: directory

- name: Copy the LAMP module
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ puppet_modules_dir }}/lamp/manifests/"
    mode: "0644"
    validate: "{{ puppet_agent_validate_cmd }} %s"
  loop:
    - manifests/init.pp
    - manifests/mysql.pp
    # - manifests/apache.pp

- name: Copy the site manifest
  ansible.builtin.copy:
    src: manifests/site.pp
    dest: "{{ puppet_manifests_dir }}/"
    mode: "0644"
    validate: "{{ puppet_agent_validate_cmd }} %s"

- name: Install puppet mysql module
  ansible.builtin.command:
    cmd: "{{ puppet_agent_bin }} module install puppetlabs-mysql --version 15.0.0"
    creates: "{{ puppet_modules_dir }}/mysql/metadata.json"
