---
- name: Converge
  hosts: all
  diff: true
  become: true
  tasks:
    - name: Include Puppet install role
      ansible.builtin.include_role:
        name: geerlingguy.puppet

    - name: Include Lamp-Puppet role
      ansible.builtin.include_role:
        name: lamp-puppet
