---
- name: Converge
  hosts: all
  diff: true
  become: true
  tasks:
    - name: Include Puppet install role
      ansible.builtin.include_role:
        name: geerlingguy.puppet

    - name: Start and enable Puppet server
      ansible.builtin.systemd:
        name: puppetserver
        state: started
        enabled: true
      when: inventory_hostname == "server"

    # Agent config: https://www.puppet.com/docs/puppet/8/install_agents

    - name: Add hosts entry to Puppet server
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ puppet_server_ip }} {{ puppet_server_name }}"
        state: present

    - name: Configure server setting
      community.general.ini_file:
        path: "{{ puppet_agent_config_path }}/puppet.conf"
        section: main
        option: server
        value: "{{ puppet_server_name }}"
        state: present
        mode: "0644"
        backup: true
      when: inventory_hostname == "agent"

    - name: Start and enable Puppet agent
      ansible.builtin.systemd:
        name: puppet
        state: started
        enabled: true
      when: inventory_hostname == "agent"

    - name: Sign server certs
      ansible.builtin.command:
        cmd: "{{ puppet_server_bin }} ca sign --all"
        creates: "{{ puppet_server_config_path }}/ca/signed/agent..pem"
      when: inventory_hostname == "server"
      register: puppet_server_certs_sign
      delay: 5
      retries: 10
      until: puppet_server_certs_sign is not failed

    - name: Connect agent to server
      ansible.builtin.command:
        cmd: "{{ puppet_agent_bin }} ssl bootstrap"
      when: inventory_hostname == "agent"
      register: puppet_bootstrap_cmd
      delay: 5
      retries: 10
      until: puppet_bootstrap_cmd is not failed
      changed_when: puppet_bootstrap_cmd.rc != 0
