---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: server
    box: ubuntu/jammy64
    memory: 1024
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.56.20"'
  - name: agent-ubuntu
    box: ubuntu/jammy64
    memory: 1024
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.56.22"'
      - "vm.network 'forwarded_port', guest: 80, host: 8022"
provisioner:
  name: ansible
  # config_options:
  #   defaults:
  #     # Show tasks timing and results at end of play
  #     callbacks_enabled: ansible.posix.profile_tasks
  env:
    # Allows placing roles in whatever path
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    group_vars:
      all:
        # Puppet role variables: https://github.com/GustavoAV/ansible-role-puppet#role-variables
        puppet_default_memory: 512m
        # puppet_service_manage: true
        # puppet_service_enabled: true
        # # Local role variables
        # apache_website_name: example
        # mysql_db_host: localhost
        # mysql_db_user: user
        # mysql_db_pass: pass
        # mysql_db_name: app_db
        # mysql_root_password: supersecret
verifier:
  name: ansible
