---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: ub22
    box: ubuntu/jammy64
    memory: 1024
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.56.20"'
      - "vm.network 'forwarded_port', guest: 80, host: 8120"
provisioner:
  name: ansible
  config_options:
    defaults:
      # Show tasks timing and results at end of play
      callbacks_enabled: ansible.posix.profile_tasks
      stdout_callback: yaml
  inventory:
    group_vars:
      all:
        puppet_target_ip: 192.168.56.20
        puppet_bolt_bin: /opt/puppetlabs/bin/bolt
verifier:
  name: ansible
